owner: agenziabergamaschi
repo: st-status

sites:
  - name: Coworking Spazio Tricolore
    url: https://spaziotricolore.it

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /st-status
  logoUrl: https://spaziotricolore.it/icon/icon-1024x1024.png
  name: Coworking Spazio Tricolore - Internet Service Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/agenziabergamaschi/st-status)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/agenziabergamaschi/st-status

workflowSchedule:
  graphs: "4 0 * * *"
  responseTime: "4 23 * * *"
  staticSite: "4 1 * * *"
  summary: "4 0 * * *"
  updateTemplate: "4 0 * * *"
  updates: "4 3 * * *"
  uptime: "3/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
